language: python

python:
  - 2.7

before_install:
  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gfortran-4.9
  - sudo ln -fs /usr/bin/gfortran-4.9 gfortran
  - sudo pip install FoBiS.py
  - wget http://rfsber.home.xs4all.nl/Robo/robodoc-4.99.41.tar.gz
  - gunzip robodoc-4.99.41.tar.gz
  - tar -xvf robodoc-4.99.41.tar
  - cd robodoc-4.99.41
  - ./configure
  - make
  - cd $TRAVIS_BUILD_DIR
  - export PATH="$TRAVIS_BUILD_DIR/robodoc-4.99.41/Source:$PATH"

before_script:
  - ./build.sh

script:
  - ./bin/json
